apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secretName | quote }}
  namespace: {{ .Values.namespace | default "default" | quote }}
type: Opaque
data:
  POSTGRES_DB: {{ .Values.database.auth.dbName | b64enc | quote }}
  POSTGRES_USER: {{ .Values.database.auth.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.auth.password | b64enc | quote }}