apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.host | quote }}
  namespace: {{ .Values.namespace | default "default" | quote }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.database.host | quote }}
  ports:
    - protocol: TCP
      port: {{ .Values.database.port }}
      targetPort: {{ .Values.database.port }}