apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-front-service"
  namespace: {{ .Values.namespace | default "default" | quote }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: {{ .Values.frontend.labels.app | quote }}
  ports:
  - protocol: "TCP"
    port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
    {{- if eq .Values.frontend.service.type "NodePort" }}
    nodePort: {{ .Values.frontend.service.nodePort | default 30201 }}
    {{- end }}