apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-front-depl"
  namespace: {{ .Values.namespace | default "default" | quote }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.labels.app | quote }}
      track: {{ .Values.frontend.labels.track | quote }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.labels.app | quote }}
        track: {{ .Values.frontend.labels.track | quote }}
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
        - name: nginx
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx", "-s", "quit"]
          env:
            - name: VITE_SOCKET_URL
              value: {{ .Values.frontend.env.vite }}