apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{ .Release.Name }}-backend-monitor"
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: {{ .Values.backend.labels.app | quote }}
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace | default "default" }}
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: 15s