namespace: pixelwar

database:
  host: "postgresdb"
  port: "5432"
  secretName: db-credentials
  auth:
    dbName: "testDB"
    user: "testUser"
    password: "testPassword"

postgresql:
  image:
    repository: postgres
    tag: "15-alpine"
  persistence:
    size: 5Gi
    accessMode: ReadWriteOnce
    mountPath: /var/lib/postgresql/data
    subPath: postgres

frontend:
  replicaCount: 1
  image:
    repository: app-frontend
    tag: v1
    pullPolicy: IfNotPresent
  labels:
    app: frontend
    track: stable
  service:
    type: LoadBalancer
    port: 80
    targetPort: 80
  env:
    vite: http://pixel-war-backend:3000

backend:
  replicaCount: 1
  image:
    repository: app-backend
    tag: v1
    pullPolicy: IfNotPresent
  labels:
    app: backend
    track: stable
  service:
    type: NodePort
    port: 3000
    targetPort: 3000
  env:
    redis: redis://redis-service:6379
    postgres: postgres://postgres:password@postgresdb:5432/pixelwar