namespace: pixelwar

replicaCount: 1

database:
  host: "postgresdb"
  port: "5432"
  secretName: db-credentials
  auth:
    dbName: "testDB"
    user: "testUser"
    password: "testPassword"
  secretName: db-credential

postgresql:
  image:
    repository: postgres
    tag: "15-alpine"
  persistence:
    size: 5Gi
    accessMode: ReadWriteOnce
    mountPath: /var/lib/postgresql/data
    subPath: postgres

labels:
  app: backend
  track: stable

service:
  type: NodePort
  port: 3000
  targetPort: 3000

backend:
  replicaCount: 1
  image:
    repository: app-backend
    tag: latest
    pullPolicy: IfNotPresent
  labels:
    app: backend
    track: stable
  service:
    type: NodePort
    port: 3000
    targetPort: 3000

frontend:
  replicaCount: 1
  image:
    repository: app-frontend
    tag: latest
    pullPolicy: IfNotPresent
  labels:
    app: frontend
    track: stable
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
  