# Stockage du secret (mot de passe protégé)
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  # Valeurs à encoder en base64 (echo -n 'monpass' | base64)
  POSTGRES_DB: dGVzdERC
  POSTGRES_USER: dGVzdFVzZXI=
  POSTGRES_PASSWORD: dGVzdFBhc3N3b3Jk