---
apiVersion: v1
kind: Service
metadata:
  name: pixelwar-back-service
  namespace: pixelwar
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
...