---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixelwar-back-depl
  namespace: pixelwar
spec:
  selector:
    matchLabels:
      app: backend
      track: stable
  replicas: 3
  template:
    metadata:
      labels:
        app: backend
        track: stable
    spec:
      containers:
        - name: backend-app
          image: "app-backend:v1"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
...