---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixelwar-front-depl
spec:
  selector:
    matchLabels:
      app: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
        track: stable
    spec:
      containers:
        - name: nginx
          image: "app-frontend:v1"
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]
...