---
apiVersion: v1
kind: Service
metadata:
  name: pixelwar-front-service
  namespace: pixelwar
spec:
  selector:
    app: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
...