name: CI Pixel War

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Backend
        run: |
          cd backend
          docker build -t pixelwar-backend:latest .

      - name: Build Frontend
        run: |
          cd frontend
          docker build -t pixelwar-frontend:latest .